---

- name: Check if Magento2 already installed
  stat:
    path: "{{ siteworx_docroot }}/app/bootstrap.php"
  register: app_bootstrap

- name: Install Magento2
  shell: >
    /usr/nexkit/bin/nkmagento2 install
    --auto-create-database
    --assume-yes
    --admin-user={{ nex_app_username | quote }}
    --admin-pass={{ nex_app_password | quote }}
    --admin-email={{ nex_app_email | quote }}
    --admin-location={{ nex_app_admin_location }}
    --base-url={{ nex_app_base_url }}
    --secure-base-url={{ nex_app_secure_base_url }}
    {{ siteworx_docroot }}
  when: not app_bootstrap.stat.exists
  register: app_installation

- name: Set up Magento2 log rotation
  shell: >
    /usr/nexkit/bin/nkmagento2 repair
    --enable-log-rotation
    {{ siteworx_docroot }}
  when: app_installation.changed

- name: Set Magento2 Cache Storage to Redis
  shell: >
    /usr/nexkit/bin/nkmagento2 repair
    --set-cache-method=redis
    --socket-path=/var/run/redis-multi-{{ nex_app_unixuser | quote }}.redis/redis.sock
    {{ siteworx_docroot }}
  when: app_installation.changed
