
- name: Set Base InterWorx Settings
  command: >
    nodeworx
    -unv
    -c Settings
    -a edit
    --iworx_fileman=0
    --iworx.passwords_length=16
    --apache_sni_enabled=1
    --siteworx.logs_savexferlogs=7
    --siteworx.logs_saveerrlogs=7
    --stats.awstats_enabled=1
    --stats.analog_enabled=0
    --stats.webalizer_enabled=0
    --rrd_ping_host=nexcess.net

- name: Set FTP to Port 990
  command: >
    sed -i 's/^Port.*21$/Port  990/g' /etc/proftpd.conf

#- name: Set FTP InterWorx Settings
#  command: >
#    nodeworx
#    -unv
#    -c Ftp
#    -a serverOptions
#    --tlsrequired=1
