---
- name: Check For Existing Vhost File
  stat:
    path="/etc/httpd/conf.d/vhost_{{ ansible_fqdn }}.conf"
  register: vhost_file_result

- name: Generate a Random Password
  set_fact:
    random_password: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters') }}"

- name: Add Server Name Siteworx Account
  command: >
    nodeworx
    -unv
    -c Siteworx
    -a add
    --master_domain "{{ ansible_fqdn }}"
    --uniqname "server"
    --nickname "NEXCESS.NET"
    --email "admin@nexcess.net"
    --password "{{ random_password }}"
    --confirm_password "{{ random_password }}"
    --master_domain_ipv4 "{{ ansible_default_ipv4.address }}"
    --database_server localhost
    --OPT_STORAGE 100
    --OPT_BANDWIDTH 99
    --OPT_EMAIL_ALIASES 0
    --OPT_EMAIL_AUTORESPONDERS 0
    --OPT_EMAIL_BOXES 0
    --OPT_EMAIL_GROUPS 0
    --OPT_FTP_ACCOUNTS 0
    --OPT_MYSQL_DBS 0
    --OPT_MYSQL_DB_USERS 0
    --OPT_POINTER_DOMAINS 0
    --OPT_SLAVE_DOMAINS 0
    --OPT_SUBDOMAINS 0
    --OPT_BACKUP 1
    --OPT_CGI_ACCESS 0
    --OPT_CRONTAB 0
    --OPT_DNS_RECORDS 0
    --OPT_SSL 1
    --OPT_BURSTABLE 1
    --OPT_SAVE_XFER_LOGS 1
    --restart_httpd 1
    --catchall_access 0
    --php_version system-php
    --php_available system-php
  register: siteworx_add_result
  when:
    - vhost_file_result.stat.exists == false

- name: Enable LetsEncrypt Plugin
  command: >
    nodeworx
    -unv
    -c Plugins
    -a edit
    --plugin_name lets-encrypt
    --status 1
  register: letsencrypt_enable_result

- name: Check For Existing Certificate File
  stat:
    path="/home/server/var/{{ ansible_fqdn }}/ssl/{{ ansible_fqdn }}.crt"
  register: cert_file_result

- name: Generate LetsEncrypt Certificate
  command: >
    siteworx
    -unv
    --login_domain "{{ ansible_fqdn }}"
    -c Ssl
    -a generateLetsEncrypt
    --domain "{{ ansible_fqdn }}"
    --commonName "{{ ansible_fqdn }}"
  register: letsencrypt_generate_result
  when:
    - cert_file_result.stat.exists == false

- name: Install Certificate to Server Services
  command: >
    nodeworx
    -unv
    -c Ssl
    -a updateall
    --cert_source domain
    --domain "{{ ansible_fqdn }}"
    --restart_now 1
  register: install_cert_result
